export const Agreement = "Agreement" // 用户协议
export const SplitLine = 'SplitLine' // 分割线
export const Button = "Button" // 按钮
export const CountDown = "CountDown"  //倒计时
export const CustomWidget = "CustomWidget" // 自定义组件
export const Checkbox = 'Checkbox'  // 选择框
export const DatePicker = 'DatePicker' //日期选择器
export const ChildList = 'ChildList' //表单内容区
export const HPicker = 'HPicker' //横向滑动单选
export const Input = 'Input'   // 输入框
export const Phone = 'Phone'  // 手机
export const RandomCode = "RandomCode"  //随机码
export const Select = 'Select'  // 下拉选择
export const Switch = 'Switch'  // 开关
export const ImgShow = "ImgShow" // 图片展示
export const ImgSlide = "ImgSlide"  //图片轮播
export const Marquee = "Marquee" // 跑马灯
export const MarqueeSingle = "MarqueeSingle" // 跑马灯-单个
export const Sms = "Sms" // 短信
export const StaticText = "StaticText" // 文本描述
export const Tabs = "Tabs"  //tabs标签
export const VideoPlay = "VideoPlay" // 视频播放
export const Wechat = "Wechat" // 微信关注